## 1. Python: Numpy
- Python의 dynamically typed programming특성상 변수는 value와 type을 모두 저장하여 용량이 크고 시간이 오래 걸림
- 이러한 단점을 극복하기 위해 Numpy가 개발 됨, Numpy의 array는 list보다 100배 가량 빠름
- 따라서 Numpy의 array는 같은 type의 데이터만 저장함

### 그럼 TensowFlow는 왜 필요함?
- TensorFlow는 연산과정을 그래프화하여 시각화 할 수 있다.
- 모든 계산과정의 설계도를 짬 (Computational Graph)
- 이 위에 데이터만 입력하면 됨력하면 됨
- 최적화 (최대화 , 최소화) Gradiant계산이 용이, 값의 변화과정을 시각화하여 관찰할 수 있다는 장점이 있음

### Pandas는 왜 필요함?
- Panel Data
- 다양한 데이터 처리에 용이이터 처리에 용이, missing data가 있는 data set도 쉽게 다룰 수 있음

In [2]:
import numpy as np

In [13]:
a = np.array([7, 8, 9, 10, 11])
print(f'{a}\n{"object type:":>12} {type(a)} \n{"data type:":>12} {a.dtype} \n{"shape:":>12} {a.shape} \n{"dimension:":>12} {a.ndim} \n{"array size:":>12} {a.size}')
a1 = np.array([a])
print(a1.shape)
print(a1)

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (5,) 
  dimension: 1 
 array size: 5
(1, 5)
[[ 7  8  9 10 11]]


### list는
1. comma (,)로 element가 구분됨
2. 다른 type의 element가 각각 다른 공간을 차지함

### array는
1. blank ()로 구분됨
2. 같은 type의 element가 각각 같은 공간을 차지함 (가장 큰 숫자가 차지하는 데이터의 크기로 통일)

In [14]:
b = np.array([[1.0, 2, 3, 4, 5], [8, 9, 10, 11, 12.2]])
print(f'{b}\n{"object type:":>12} {type(b)} \n{"data type:":>12} {b.dtype} \n{"shape:":>12} {b.shape} \n{"dimension:":>12} {b.ndim} \n{"array size:":>12} {b.size}')
b1 = np.array([b])
print(b1.shape)
print(b1)

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type: <class 'numpy.ndarray'> 
  data type: float64 
      shape: (2, 5) 
  dimension: 2 
 array size: 10
(1, 2, 5)
[[[ 1.   2.   3.   4.   5. ]
  [ 8.   9.  10.  11.  12.2]]]


In [15]:
c = np.array([[[1, 2, 3, 4, 5], [8, 9, 10, 11, 12]], [[4, 5, 6, 7, 8], [10, 11, 12, 13, 14]]])
print(f'{c}\n{"object type:":>12} {type(c)} \n{"data type:":>12} {c.dtype} \n{"shape:":>12} {c.shape} \n{"dimension:":>12} {c.ndim} \n{"array size:":>12} {c.size}')
c1 = np.array([c])
print(c1.shape)
print(c1)

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (2, 2, 5) 
  dimension: 3 
 array size: 20
(1, 2, 2, 5)
[[[[ 1  2  3  4  5]
   [ 8  9 10 11 12]]

  [[ 4  5  6  7  8]
   [10 11 12 13 14]]]]


In [16]:
ac1 = np.array([[[1, 2, 3, 4, 5], [8, 9, 10, 11, 12]]])
print(f'{ac1}\n{"object type:":>12} {type(ac1)} \n{"data type:":>12} {ac1.dtype} \n{"shape:":>12} {ac1.shape} \n{"dimension:":>12} {ac1.ndim} \n{"array size:":>12} {ac1.size}')
print(ac1.shape)
print(ac1)

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (1, 2, 5) 
  dimension: 3 
 array size: 10
(1, 2, 5)
[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]


In [17]:
ac2 = np.array([[[1, 2, 3, 4, 5]]])
print(f'{ac2}\n{"object type:":>12} {type(ac2)} \n{"data type:":>12} {ac2.dtype} \n{"shape:":>12} {ac2.shape} \n{"dimension:":>12} {ac2.ndim} \n{"array size:":>12} {ac2.size}')
print(ac2.shape)
print(ac2)

[[[1 2 3 4 5]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (1, 1, 5) 
  dimension: 3 
 array size: 5
(1, 1, 5)
[[[1 2 3 4 5]]]


## 2. Numpy: special arrays and indexing