## 1. Python: Numpy
- Python의 dynamically typed programming특성상 변수는 value와 type을 모두 저장하여 용량이 크고 시간이 오래 걸림
- 이러한 단점을 극복하기 위해 Numpy가 개발 됨, Numpy의 array는 list보다 100배 가량 빠름
- 따라서 Numpy의 array는 같은 type의 데이터만 저장함

### 그럼 TensowFlow는 왜 필요함?
- TensorFlow는 연산과정을 그래프화하여 시각화 할 수 있다.
- 모든 계산과정의 설계도를 짬 (Computational Graph)
- 이 위에 데이터만 입력하면 됨력하면 됨
- 최적화 (최대화 , 최소화) Gradiant계산이 용이, 값의 변화과정을 시각화하여 관찰할 수 있다는 장점이 있음

### Pandas는 왜 필요함?
- Panel Data
- 다양한 데이터 처리에 용이이터 처리에 용이, missing data가 있는 data set도 쉽게 다룰 수 있음

In [1]:
import numpy as np

In [13]:
a = np.array([7, 8, 9, 10, 11])
print(f'{a}\n{"object type:":>12} {type(a)} \n{"data type:":>12} {a.dtype} \n{"shape:":>12} {a.shape} \n{"dimension:":>12} {a.ndim} \n{"array size:":>12} {a.size}')
a1 = np.array([a])
print(a1.shape)
print(a1)

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (5,) 
  dimension: 1 
 array size: 5
(1, 5)
[[ 7  8  9 10 11]]


### list는
1. comma (,)로 element가 구분됨
2. 다른 type의 element가 각각 다른 공간을 차지함

### array는
1. blank ()로 구분됨
2. 같은 type의 element가 각각 같은 공간을 차지함 (가장 큰 숫자가 차지하는 데이터의 크기로 통일)

In [14]:
b = np.array([[1.0, 2, 3, 4, 5], [8, 9, 10, 11, 12.2]])
print(f'{b}\n{"object type:":>12} {type(b)} \n{"data type:":>12} {b.dtype} \n{"shape:":>12} {b.shape} \n{"dimension:":>12} {b.ndim} \n{"array size:":>12} {b.size}')
b1 = np.array([b])
print(b1.shape)
print(b1)

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type: <class 'numpy.ndarray'> 
  data type: float64 
      shape: (2, 5) 
  dimension: 2 
 array size: 10
(1, 2, 5)
[[[ 1.   2.   3.   4.   5. ]
  [ 8.   9.  10.  11.  12.2]]]


In [14]:
c = np.array([[[1, 2, 3, 4, 5], [8, 9, 10, 11, 12]], [[4, 5, 6, 7, 8], [10, 11, 12, 13, 14]]])
print(f'{c}\n{"object type:":>12} {type(c)} \n{"data type:":>12} {c.dtype} \n{"shape:":>12} {c.shape} \n{"dimension:":>12} {c.ndim} \n{"array size:":>12} {c.size}')
c1 = np.array([c])
print(c1.shape)
print(c1)

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (2, 2, 5) 
  dimension: 3 
 array size: 20
(1, 2, 2, 5)
[[[[ 1  2  3  4  5]
   [ 8  9 10 11 12]]

  [[ 4  5  6  7  8]
   [10 11 12 13 14]]]]


In [16]:
ac1 = np.array([[[1, 2, 3, 4, 5], [8, 9, 10, 11, 12]]])
print(f'{ac1}\n{"object type:":>12} {type(ac1)} \n{"data type:":>12} {ac1.dtype} \n{"shape:":>12} {ac1.shape} \n{"dimension:":>12} {ac1.ndim} \n{"array size:":>12} {ac1.size}')
print(ac1.shape)
print(ac1)

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (1, 2, 5) 
  dimension: 3 
 array size: 10
(1, 2, 5)
[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]]


In [17]:
ac2 = np.array([[[1, 2, 3, 4, 5]]])
print(f'{ac2}\n{"object type:":>12} {type(ac2)} \n{"data type:":>12} {ac2.dtype} \n{"shape:":>12} {ac2.shape} \n{"dimension:":>12} {ac2.ndim} \n{"array size:":>12} {ac2.size}')
print(ac2.shape)
print(ac2)

[[[1 2 3 4 5]]]
object type: <class 'numpy.ndarray'> 
  data type: int32 
      shape: (1, 1, 5) 
  dimension: 3 
 array size: 5
(1, 1, 5)
[[[1 2 3 4 5]]]


## 2. Numpy: special arrays and indexing

- filling arrays with specific values: all type = float64 except for 'full'

In [8]:
a_zeros = np.zeros((2, 3))
print(a_zeros)
a_ones = np.ones((2, 4), dtype = int)
print(a_ones)
a_full = np.full((2, 5), 7)
print(a_full)
print(np.eye(3)) # identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# filling an array with random flaots: in the half-open interval [0.0, 1.0)
a_ran = np.random.random((2, 3, 4))
print(f'{a_ran} \n\n {a_ran.dtype}')

[[[0.74599555 0.20250158 0.44100925 0.31632154]
  [0.57506755 0.04078832 0.39623542 0.39850111]
  [0.41176533 0.20604485 0.14687682 0.04754668]]

 [[0.80919247 0.6732917  0.36211623 0.57454004]
  [0.89516632 0.65096532 0.82636269 0.49358314]
  [0.71834392 0.83235902 0.59113364 0.58827024]]] 

 float64


In [24]:
# array indexing
print(c)
print(c[1, 0, 4])
print(c[1][0][4])
print()
print(c[0, 0, 4])
print(c[0][0][4])


[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
8
8

5
5


## 3. NumPy: flattening and making arrays with arange function

- flattening은 다차원 배열을 1차원 배열로 바꾸는 것

### 복습
- list 는 모든 element가 comma & space로 구분되어 있고, np.array는 space로 구분되어있다.

In [40]:
# flattening
print(c)
print()
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n\n\n{np.array(l)}\n')


# flattening 
print(np.array(c.flat))

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]

[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]


[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]

[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


### list 에서는 range, array 에서는 arange를 쓴다. (arange = array range)

In [48]:
# making an array with arange with a same interval
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1, 3, 7))

print()

h = np.arange(5, 21, 2) # 5 이상 21 미만 2 간격으로
print(h)
print(np.arange(1, 21).reshape(2, 10))

# creating an array of equal space within a range
a_ss = np.linspace(0, 1, 11) # 보통 x축 찍을 때 , 구간 내에서 동일한 간격으로 array만들어 줌
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11


## 4. NumPy: Array operations
- operations on all elements of arrays

In [62]:
# element-wise operations -- 원소별 연산
# dimension이 일치하는 matrix를 dotproduct
xa = np.array([[1, 2],[3, 4],[5, 6]])
xb = np.array([[3, 4],[5, 6],[7, 8]])

print(xa)
print()
print(xb)
print()
print(xa.shape, xb.shape)
print()
print(f'{xa+xb}\n\n{xa*2}')
print()
print(xa*xb)

[[1 2]
 [3 4]
 [5 6]]

[[3 4]
 [5 6]
 [7 8]]

(3, 2) (3, 2)

[[ 4  6]
 [ 8 10]
 [12 14]]

[[ 2  4]
 [ 6  8]
 [10 12]]

[[ 3  8]
 [15 24]
 [35 48]]


In [64]:
# element-wise operations -- 원소별 연산
print(np.add(xa, xb))
print()
print(np.subtract(xa, xb))
print()
print(np.multiply(xa, xb))
print()
print(np.sqrt(xa))

[[ 4  6]
 [ 8 10]
 [12 14]]

[[-2 -2]
 [-2 -2]
 [-2 -2]]

[[ 3  8]
 [15 24]
 [35 48]]

[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


- inner product
- 행렬의 inner product 연산의 경우 두 행렬의 정합성이 맞아야 한다. 

In [73]:
# inner product of matrix
xc = np.ones((2, 1))
print(xc) ; print()
print(xc.shape, xc.ndim) ; print()
print(xa.dot(xc)) # dot() as a method
print(np.dot(xb, xc))

[[1.]
 [1.]]

(2, 1) 2

[[ 3.]
 [ 7.]
 [11.]]
[[ 7.]
 [11.]
 [15.]]


In [68]:
# inner product of matrix
xd = np.array([[1, 2],[1, 2]]) ; print(xd)
print()
print(np.dot(xa, xd)) ; print(np.dot(xb, xd))

[[1 2]
 [1 2]]

[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [77]:
# transposing
print(xa.T)
print(xb + 3)
print(xb)
xb += 3
print(xb)

[[1 3 5]
 [2 4 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[3 4]
 [5 6]
 [7 8]]
[[ 6  7]
 [ 8  9]
 [10 11]]


## 5. NumPy: Broadcating
- Arithmetic operation between difference shaped arrays
- Broadcating rule이 적용되면 차원이 다른 matrix간의 연산이 가능해진다.
- 


In [85]:
ya = np.arange(1, 10).reshape(3, 3); print(ya)
yv1 = np.ones((3, 1)); print(yv1)

yb = ya + yv1 ; print(yb)

yv2 = np.full((1, 3), 2) ; print(yv2)

yc = ya + yv2; print(yc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.]
 [1.]
 [1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
